In [1]:
# pip install numpy

import numpy as np

In [2]:

vector = np.array([1, 2, 3, 4, 5])
print(f"آرایه یک بعدی:\n{vector}")

matrix = np.array([[10, 20, 30],
                   [40, 50, 60]])
print(f"\nآرایه دو بعدی (ماتریس):\n{matrix}")

zeros = np.zeros((3, 4))   
ones = np.ones((2, 3))   
range_array = np.arange(0, 10, 2) 
print(f"\nآرایه Range:\n{range_array}")

آرایه یک بعدی:
[1 2 3 4 5]

آرایه دو بعدی (ماتریس):
[[10 20 30]
 [40 50 60]]

آرایه Range:
[0 2 4 6 8]


In [3]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f"شکل (Shape) آرایه A: {A.shape}")  
print(f"ابعاد (Dimension) آرایه A: {A.ndim}") 
print(f"تعداد کل عناصر: {A.size}")
print(f"نوع داده عناصر: {A.dtype}")     

شکل (Shape) آرایه A: (3, 3)
ابعاد (Dimension) آرایه A: 2
تعداد کل عناصر: 9
نوع داده عناصر: int64


In [4]:

print(f"عنصر ردیف 1، ستون 2 (ایندکس 0 شروع می‌شود): {A[1, 2]}")

column_2 = A[:, 1]
print(f"ستون دوم: {column_2}") 

subset = A[:2, :2]
print(f"زیرمجموعه 2x2:\n{subset}") 

عنصر ردیف 1، ستون 2 (ایندکس 0 شروع می‌شود): 6
ستون دوم: [2 5 8]
زیرمجموعه 2x2:
[[1 2]
 [4 5]]


In [5]:
flat_array = np.arange(12)
print(f"آرایه تخت: {flat_array}")

reshaped_matrix = flat_array.reshape(3, 4)
print(f"\nآرایه تغییر شکل داده شده 3x4:\n{reshaped_matrix}")

آرایه تخت: [ 0  1  2  3  4  5  6  7  8  9 10 11]

آرایه تغییر شکل داده شده 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


عملیات عنصر به عنصر

In [6]:
A = np.array([1, 2, 3])
B = np.array([10, 20, 30])

Sum_AB = A + B
Product_AB = A * B
print(f"جمع عنصر به عنصر A + B: {Sum_AB}")     # [11 22 33]
print(f"ضرب عنصر به عنصر A * B: {Product_AB}") # [10 40 90]


Scaled_A = A * 2
print(f"ضرب A در 2: {Scaled_A}") # [2 4 6]

جمع عنصر به عنصر A + B: [11 22 33]
ضرب عنصر به عنصر A * B: [10 40 90]
ضرب A در 2: [2 4 6]


توابع آماری

In [7]:
data = np.array([[1, 5, 9],
                 [2, 6, 10]])

print(f"میانگین کل: {np.mean(data)}")        
print(f"میانگین بر اساس ستون (axis=0): {np.mean(data, axis=0)}") 
print(f"حداکثر مقدار: {np.max(data)}")        

میانگین کل: 5.5
میانگین بر اساس ستون (axis=0): [1.5 5.5 9.5]
حداکثر مقدار: 10



ضرب ماتریسی (Dot Product)



In [8]:
X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])

Z = X @ Y 
print(f"ضرب ماتریسی (X @ Y):\n{Z}") 

ضرب ماتریسی (X @ Y):
[[19 22]
 [43 50]]


<div dir="rtl">
حل سیستم معادلات خطی

یکی از قدرتمندترین کاربردهای جبر خطی، حل سیستم‌های معادلات خطی است (مثلاً $Ax=b$)


فرض کنید سیستم زیر را داریم:

<div dir="ltr">

$2x + 3y = 8$

$x + y = 3$
</div>

این را می‌توان به صورت ماتریسی نوشت:

<div dir="ltr">

$A = [[2, 3], [1, 1]]$

$b = [8, 3]$
</div>

 حل سیستم معادلات خطی (x = A⁻¹b)
 
</div>

In [9]:
A = np.array([[2, 3], [1, 1]])
b = np.array([8, 3])

#
solution = np.linalg.solve(A, b)

print(f"ماتریس ضرایب A:\n{A}")
print(f"بردار جواب b: {b}")
print(f"حل (x, y): {solution}")

ماتریس ضرایب A:
[[2 3]
 [1 1]]
بردار جواب b: [8 3]
حل (x, y): [1. 2.]


Boolean Indexing and Filtering

In [10]:

data = np.array([10, 15, 22, 5, 8, 30, 12])

condition = data > 10 
print(f"آرایه بولین: {condition}")

filtered_data = data[condition]
print(f"داده‌های فیلتر شده: {filtered_data}")

آرایه بولین: [False  True  True False False  True  True]
داده‌های فیلتر شده: [15 22 30 12]


Determinant

In [11]:
B = np.array([[1, 2, 3], 
              [4, 5, 6]])

B_T = B.T
print(f"ماتریس B (2x3):\n{B}")
print(f"\nترانهاده B^T (3x2):\n{B_T}")

ماتریس B (2x3):
[[1 2 3]
 [4 5 6]]

ترانهاده B^T (3x2):
[[1 4]
 [2 5]
 [3 6]]


Normalization

In [12]:
data = np.array([10, 15, 20, 25, 30])

normalized_data = (data - np.mean(data)) / np.std(data)
print(f"داده نرمال شده: {normalized_data}")

داده نرمال شده: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
